name: Build OpenWrt x86_64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex g++ gawk gcc-multilib \
          git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
          file wget python3 python3-pip time

    - name: Clone OpenWrt and configure feeds
      run: |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt

        # 使用 HTTPS 添加 feeds，防止 SSH 公钥报错
        cat <<EOF > feeds.conf.default
src-git packages https://github.com/openwrt/packages.git
src-git luci https://github.com/openwrt/luci.git
src-git routing https://github.com/openwrt-routing/packages.git
src-git telephony https://github.com/openwrt/telephony.git
src-git passwall https://github.com/xiaorouji/openwrt-passwall.git
src-git vlmcsd https://github.com/Wind4/vlmcsd.git
EOF

    - name: Update and install feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Copy custom .config
      run: |
        cp .config openwrt/.config

    - name: Prepare build environment
      run: |
        cd openwrt
        make defconfig

    - name: Build OpenWrt firmware
      run: |
        cd openwrt
        make -j$(nproc) download
        make -j$(nproc) V=s

    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt-x86_64
        path: openwrt/bin/targets/x86/64/
