name: Build OpenWrt x86_64 with Passwall & Vlmcsd

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3 python3-pip python3-venv rsync unzip zlib1g-dev file wget

    - name: Clone OpenWrt
      run: |
        git clone https://github.com/openwrt/openwrt -b master openwrt
        cp feeds.conf.default openwrt/
                 
    - name: Modify LAN IP
      run: |
        cd openwrt
        sed -i 's/192.168.1.1/192.168.5.5/g' package/base-files/files/bin/config_generate

    - name: Add Passwall feed
      run: |
        cd openwrt
        echo "src-git passwall https://github.com/xiaorouji/openwrt-passwall" >> feeds.conf.default
        echo "src-git passwall_packages https://github.com/xiaorouji/openwrt-passwall-packages" >> feeds.conf.default
        echo "CONFIG_PACKAGE_luci=y" >> .config
        ./scripts/feeds update passwall passwall_packages
        ./scripts/feeds install -a -p passwall
        ./scripts/feeds install -a -p passwall_packages

    - name: Update & Install feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Tmate SSH (debug if needed)
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 20
      if: always()

    - name: Configure default settings
      run: |
        cd openwrt
        make defconfig
        ./scripts/diffconfig.sh > seed.config

    - name: Build OpenWrt
      run: |
        cd openwrt
        make -j$(nproc) download V=s
        make -j$(nproc) V=s

    - name: Upload Firmware
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-x86_64
        path: openwrt/bin/targets/x86/64/
