name: Build OpenWrt with Passwall and Vlmcsd

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile OpenWrt

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev rsync unzip zlib1g-dev file wget python3 python3-venv python3-pip

    - name: Clone OpenWrt official repo
      run: |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        git clone https://github.com/Wind4/vlmcsd.git package/vlmcsd
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Modify default LAN IP
      run: |
        sed -i 's/192.168.1.1/192.168.5.5/g' openwrt/package/base-files/files/bin/config_generate
        sudo mkdir -p package/vlmcsd

    - name: Add Passwall and vlmcsd feeds
      run: |
        cd openwrt
        echo 'src-git passwall_packages https://github.com/kenzok8/openwrt-packages.git' >> feeds.conf.default
        echo 'src-git passwall_luci https://github.com/kenzok8/small-package.git;main' >> feeds.conf.default
        #echo "src-git kenzo https://github.com/fw876/helloworld" >> feeds.conf.default
        echo "src-git vlmcsd https://github.com/Wind4/vlmcsd" >> feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Start SSH with tmate
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: false

    - name: Build OpenWrt
      if: success()
      run: |
        cd openwrt
        if [ ! -f .config ]; then
          echo "No .config found. Please connect via tmate and run make menuconfig"
          exit 1
        fi
        make defconfig
        make download -j$(nproc)
        make -j$(nproc)

    - name: Upload firmware to GitHub Releases
      if: success()
      uses: softprops/action-gh-release@v1
      with:
        files: openwrt/bin/targets/**/openwrt-*.bin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
