name: Build OpenWrt x86_64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex g++ gawk gcc-multilib \
          git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
          file wget python3 python3-pip time

    - name: Clone OpenWrt
      run: |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        # 添加 feeds 源，含 vlmcsd
        echo "src-git lienol https://github.com/xiaorouji/openwrt-passwall" >> feeds.conf.default
        echo "src-git vlmcsd https://github.com/Waachooo/vlmcsd-openwrt.git" >> feeds.conf.default

    - name: Update and install feeds with vlmcsd fallback
      run: |
        cd openwrt
        ./scripts/feeds update -a || echo "Feeds update failed, retrying..."
        ./scripts/feeds install -a || echo "Feeds install failed, retrying..."
        # 检查 vlmcsd 是否存在，没有则手动clone
        if [ ! -d feeds/vlmcsd ]; then
          echo "vlmcsd feed missing, cloning manually..."
          git clone https://github.com/Waachooo/vlmcsd-openwrt.git feeds/vlmcsd
        fi
        ./scripts/feeds install -a

    - name: Copy custom files and config
      run: |
        cp -r files openwrt/files
        cp .config openwrt/.config

    - name: Make defconfig
      run: |
        cd openwrt
        make defconfig

    - name: Compile
      run: |
        cd openwrt
        make -j$(nproc) download
        make -j$(nproc) V=s

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt-x86_64
        path: openwrt/bin
 
